name: Package Application with Pyinstaller for Windows

on:
  push:
    branches: [ gui ]
  pull_request:
    branches: [ gui ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Pull Project
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r /home/runner/work/Pokemon_capture_chance/Pokemon_capture_chance/requirements.txt
    - name: Test with pytest
      run: |
          pytest
  
  package:
    name: package
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Copy img/ folder
      run: cp -r src/img/ src/dist/windows/main

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PCC-Windows
        path: src/dist/windows/main
