name: Package Application with Pyinstaller for Windows

on:
  push:
    branches: [ gui ]
  pull_request:
    branches: [ gui ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Copy img/ folder
      run: cp src/img/ src/dist/windows/main

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PCC-Windows
        path: src/dist/windows/main
