name: Package Application with Pyinstaller for Linux

on:
  push:
    branches: [ gui ]
  pull_request:
    branches: [ gui ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: src
        spec: src/main_windows.spec

    - uses: actions/upload-artifact@v2
      with:
        name: PCC-Linux
        path: src/dist/main
